  version: 0.0
  os: linux

  files:
    - source: ./webapp.jar
      destination: ~/wabapp.jar
  hooks:
    AfterInstall:
      - location: ./codedeploy/afterInstall.sh
        timeout: 180
        runas: ubuntu
    ApplicationStart:
      - location: ./codedeploy/applicationStart.sh
        timeout: 180
        runas: ubuntu
    ApplicationStop:
      - location: ./codedeploy/applicationStop.sh
        timeout: 120
        runas: ubuntu
    BeforeInstall:
      - location: ./codedeploy/beforeInstall.sh
        timeout: 150
        runas: ubuntu

