  version: 0.0
  os: linux

  files:
    - source: ./webapp.jar
      destination: /home/
  hooks:
    AfterInstall:
      - location: ./codedeploy/afterInstall.sh
        timeout: 3600
        runas: ubuntu
    ApplicationStart:
      - location: ./codedeploy/applicationStart.sh
        timeout: 3600
        runas: ubuntu
    ApplicationStop:
      - location: ./codedeploy/applicationStop.sh
        timeout: 3600
        runas: ubuntu
    BeforeInstall:
      - location: ./codedeploy/beforeInstall.sh
        timeout: 3600
        runas: ubuntu

